### ISSUE TITLE
systemd::dropin_file::daemon_reload possible duplicate resource defintion

### ISSUE THREAD

**Issue by TheMeier** [camptocamp/puppet-systemd#116]
If you define multiple drop-in for the same service using the new systemd::dropin_file::daemon_reload parameter on more then one of them puppet will fail with a duplicate declaration error for `Exec[<servicename>.service-systemctl-daemon-reload]`.

**Comment by ekohl** [comment]
Looks like this only happens when you use `daemon_reload => 'eager'`:

https://github.com/camptocamp/puppet-systemd/blob/f0ce6f04aa89c002cd9ba721c6f5d91177f32afc/manifests/dropin_file.pp#L95-L105
