### ISSUE TITLE
How to enable/start parameterized timers?

### ISSUE THREAD

**Issue by kasimon** [camptocamp/puppet-systemd#133]
If I'm not mistaken there currently is no support for parameterized timer units, at least I have not found a way to model the result of these commands with the module:

```
systemctl enable borgwrapper-backup@<config_name>.timer
systemctl start borgwrapper-backup@<config_name>.timer
```
Could this be added or the documentation improved if this is already supported?

**Comment by traylenator** [comment]
```puppet
service{'borgwrapper-backup@foo.timer:
  ensure => true,
  enable => true,
}
```

works.

**Comment by kasimon** [comment]
@traylenator You are totally right. I had found out it in the meantime myself but forgot about this issue. Thanks!
