### ISSUE TITLE
Allow service reloading

### ISSUE THREAD

**Issue by k0ka** [camptocamp/puppet-systemd#159]
There is no easy way to use 
`systemctl reload <service>`
for a specified service. Puppet will always restart it. 

I suggest adding some parameter like `$use_reload` to `systemd::unit_file` that will set the `restart` argument of `service`.

**Comment by raphink** [comment]
That seems like a reasonable idea. Could you provide a PR for this please?

**Comment by k0ka** [comment]
Hi,

here it is https://github.com/camptocamp/puppet-systemd/pull/175
