### ISSUE TITLE
Add support to use infinity with LimitNPROC

### ISSUE THREAD

**Issue by andriimua** [camptocamp/puppet-systemd#173]
It would be nice to have a possibility to use _LimitNPROC_ with an _infinity_ option.

I've checked out PRs and see that the next PR adds this opportunity:
https://github.com/camptocamp/puppet-systemd/pull/152/files

**Reference**:
https://www.freedesktop.org/software/systemd/man/systemd.exec.html

**Comment by raphink** [comment]
Fixed in #152
