### ISSUE TITLE
Custom SystemD Unit File will be created, but its not define in Puppet hiera

### ISSUE THREAD

**Issue by haessi82517** [camptocamp/puppet-systemd#185]
Hello, 
i've following issue (Module Version 2.10):

In Hiera, i've the following Statement:

systemd::timer { 'mlocate-updatedb.timer':
    active => true,
    enable => true,
  }

By a Puppet Run, he will created a Custom Timer File:

Notice: /Stage[main]/Profile::Linux::Rhel8/Systemd::Timer[mlocate-updatedb.timer]/Systemd::Unit_file[mlocate-updatedb.timer]/File[/etc/systemd/system/mlocate-updatedb.timer]/ensure: created (corrective)

But i've no Parameter like "service_content or service_source" defined and according to the Doku , the Default Value for both are "undefined". So i expect that he doesnt create a custom systemd Unit File.

It this a bug ?

Regards
Oliver

**Comment by kenyon** [comment]
You need to provide either `timer_content` or `timer_source`. https://github.com/camptocamp/puppet-systemd#timer-units
