### ISSUE TITLE
'systemctl daemon-reload' is not qualified

### ISSUE THREAD

**Issue by craiggenner** [camptocamp/puppet-systemd#22]
When importing this module and then running spec tests I get the following:

```
Failure/Error: it { should compile.with_all_deps }
  error during compilation: Validation of Exec[systemctl-daemon-reload] failed: 'systemctl daemon-reload' is not qualified and no path was specified. Please qualify the command or specify a path. at /mnt/spec/fixtures/modules/systemd/manifests/init.pp:11
```

The fix appears to be to change:
```
  Exec {
    refreshonly => true,
    path        => $::path,
  }
```
to:
```
  Exec {
    refreshonly => true,
    path        => split($::path, ':'),
  }
```

Not sure if this breaks other things though.

**Comment by alexjfisher** [comment]
It should be fine either way.
https://docs.puppet.com/puppet/latest/types/exec.html#exec-attribute-path
> Paths can be specified as an array or as a ‘:’ separated list.

@craiggenner What does your $::path fact look like?

**Comment by craiggenner** [comment]
I would agree that it should be fine either way, but I couldn't get the tests to pass until I tried it with a `split`.

I'm not working in that environment any more so I'm not able to say what $::path is, but I should be doing something similar soon so I'll test again and let you know the results.

**Comment by raphink** [comment]
Are you still able to reproduce this?

**Comment by TheMeier** [comment]
@craiggenner this is a topic with many modules. I think there is an argument here that your test setup is incomplete. I am running all of my tests using https://github.com/mcanevet/rspec-puppet-facts nowadays for that reason. path is certainly not the only fact you want to have pre-set.
