### ISSUE TITLE
Add explicit ordering to README.md

### ISSUE THREAD

**Issue by afn** [camptocamp/puppet-systemd#24]
It would be helpful if the README file had a complete example containing both a `systemd::unit_file` and a `service` resource. In particular, it wasn't immediately obvious that the ordering needs to be made explicit:

```puppet
::systemd::unit_file { 'foo.service':
 source => "puppet:///modules/${module_name}/foo.service",
}

service { foo:
  enable  => true,
  ensure  => running,
  require => Systemd::Unit_file['foo.service']
}
```

Without the explicit ordering, Puppet will attempt to start the service before the unit file has been created.

**Comment by alexjfisher** [comment]
What's perhaps even more confusing is the service also needs to `require => Exec['systemctl-daemon-reload']`
