### ISSUE TITLE
stdlib functions are used, but no stdlib requirement in metadata.json

### ISSUE THREAD

**Issue by petems** [camptocamp/puppet-systemd#28]
> Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Unknown function: 'validate_hash'. at /etc/puppetlabs/code/environments/production/modules/systemd/manifests/service_limits.pp:13:5  at /etc/puppetlabs/code/environments/production/modules/systemd/foo.pp:1 on node localhost.localdomain

**Comment by raphink** [comment]
Fixed in c9d2e5193227ec086a63ae682b2b609cfdf86e1b
