### ISSUE TITLE
Puppet version compatibility

### ISSUE THREAD

**Issue by pouete** [camptocamp/puppet-systemd#34]
Hello puppet-systemd,
I just found that the metadata file contains incorrect information about the puppet version compatibility. 
For instance, it claims it is compatible with versions < 3.7 . However the parametrized arguments in init.pp do not agree.
Is it possible to have a cleaned up version of metadata file ?

Regards.

**Comment by ekohl** [comment]
It looks correct in git:
https://github.com/camptocamp/puppet-systemd/blob/f2ab8e6b1671730da9a9cdba5cad5c9b2be45a4f/metadata.json#L20-L25

It could use a release though to get an official Puppet 6 compatible version on the forge :)

**Comment by bastelfreak** [comment]
@raphink can you do a new release?

**Comment by ekohl** [comment]
@raphink ping? :)

**Comment by raphink** [comment]
Release merged, thanks @bastelfreak
