### ISSUE TITLE
Better test for systemd (and other init systems)

### ISSUE THREAD

**Issue by pillarsdotnet** [camptocamp/puppet-systemd#37]
The recommended test for init=systemd fails on systems where the init binary is named "/sbin/init" rather than "systemd".

The following test works on every system I've tried so far:

```
/proc/1/exe --version | grep -q 'systemd'
```

**Comment by pillarsdotnet** [comment]
Submitted Pull-Request #38 to fix the problem.

**Comment by TheMeier** [comment]
Use https://github.com/puppetlabs/puppetlabs-stdlib#service_provider instead.

**Comment by jfleury-at-ovh** [comment]
This issue is fixed by #42.
