### ISSUE TITLE
fact systemd_internal_services is empty

### ISSUE THREAD

**Issue by axxelG** [camptocamp/puppet-systemd#47]
`puppet facts` throws a warning:
> Facter: Fact resolution fact='systemd_internal_services', resolution='<anonymous>' resolved to an invalid value: Expected disabled to be one of [Integer, Float, TrueClass, FalseClass, NilClass, String, Array, Hash], but was Symbol

And there was no fact "systemd_internal_services"

Removing  `.to_sym` from `result[service] = status.to_sym` in /lib/facter/systemd.rb (line 55) fixed it for me.

**Comment by bastelfreak** [comment]
The patch is now merged. I will try to create a new release shortly.
