### ISSUE TITLE
LimitNOFILE restricted to integer type

### ISSUE THREAD

**Issue by AlbertoGarciaFdez** [camptocamp/puppet-systemd#62]
Hi, why is LimitNOFILE an integer type? AFAIK infinity can be used with LimitNOFILE on systemd.
Should not be this more appropriate?

```
    Optional['LimitNOFILE']         => Pattern['^(infinity|(\d+)$'],
```

**Comment by raphink** [comment]
LGTM. Can you turn this into a PR please?

**Comment by AlbertoGarciaFdez** [comment]
Sure, thanks!

**Comment by traylenator** [comment]
Also 'soft:hard' is also permitted.

**Comment by raphink** [comment]
Leaving this open for now for the sake of `soft:hard`
