### ISSUE TITLE
Include puppetlabs-inifile in the dependencies list

### ISSUE THREAD

**Issue by mvisonneau** [camptocamp/puppet-systemd#77]
There are a few `ini_setting` resources being used in this module. It doesn't seem included in the requirement list. I'll do a MR if/when I have some time.

**Comment by bastelfreak** [comment]
from the [services section](https://github.com/camptocamp/puppet-systemd#services):

> This requires puppetlabs-inifile, which is only a soft dependency in this module (you need to explicitly install it). Both parameters accept a string or an array.

inifile is a soft dependency. It isn't needed for everything in this module. We try to keep the list of dependencies small and only add hard dependencies. inifile is used more and more in this module, so we could argue that it is almost a hard dependency. I vote for keeping it out of the metadata.json. But if more people want to have it in I'm fine with that as well.

**Comment by trevor-vaughan** [comment]
@bastelfreak Recommend voting on https://tickets.puppetlabs.com/browse/PUP-5880

**Comment by bastelfreak** [comment]
ugh annoying this year. Hopefully this gets fixed somewhere in the future.

**Comment by alexjfisher** [comment]
This dependency has been included since https://github.com/camptocamp/puppet-systemd/pull/14.
