### ISSUE TITLE
Hiera usage for systemd::unit_file

### ISSUE THREAD

**Issue by linuxmail** [camptocamp/puppet-systemd#86]
hi,

just a short question: can I call the systemd::unit_file from Hiera too ? I tried was included the systemd class and 

```
systemd::unit_file:
  'foo':
    ensure: 'running'
    source: 'puppet:///...foo.service'
```
but it seems, that I have to use a create_resource manifest wrapper .., or maybe I just call the class wrong ...

**Comment by ekohl** [comment]
It's a define so you're correct you need some sort of wrapper for usage in hiera.

**Comment by linuxmail** [comment]
hi,

thanks.

**Comment by bastelfreak** [comment]
@linuxmail in other modules we often have an array as parameter. The manifest can iterate on that array of hashes and create the defined resource and pass each hash. If you're interested you can provide that as a PR to this module.
