### ISSUE TITLE
STIG Rule RHEL-07-021340 - The system must use a separate file system for /tmp

### ISSUE THREAD

**Issue by linuxdan** [camptocamp/puppet-systemd#90]
> Red Hat Enterprise Linux 7 Security Technical Implementation Guide
> Release: 4
> Benchmark Date: 26 Jan 2018
> Vuln ID: V-72065
> Rule ID: SV-86689r1_rule
> STIG ID: RHEL-07-021340

Check Text: Verify that a separate file system/partition has been created for "/tmp".
Check that a file system/partition has been created for "/tmp" with the following command:
`# systemctl is-enabled tmp.mount`
`enabled`
If the "tmp.mount" service is not enabled, this is a finding.
Fix Text: Start the "tmp.mount" service with the following command:
`# systemctl enable tmp.mount`

It is not obvious if the module will do this, but I am going to give it a try

**Comment by trevor-vaughan** [comment]
@linuxdan You don't. https://github.com/simp/pupmod-simp-simp/blob/master/manifests/mountpoints/tmp.pp

Turns out, we made a whole framework for just what you're trying to do.

**Comment by linuxdan** [comment]
@trevor-vaughan 
But I do not have the authority to drop SIMP into the mix.

**Comment by linuxdan** [comment]
@trevor-vaughan 
Also, after looking at your code, I suspect it would fail the check as well.
All this STIG-ish garbage I am posting comes out of Nessus scans.

Try the `systemctl is-enabled this.mount` command on your system.

**Comment by trevor-vaughan** [comment]
@linuxdan The `tmp.mount` service doesn't really have anything to do with the `systemd` module, it's just a built-in feature of EL7 and can be enabled using `systemctl` and, I believe, is on by default.

The code that I posted meets the actual STIG requirements.

Anyway, I would recommend closing this since it doesn't have anything really to do with the `systemd` module.

**Comment by linuxdan** [comment]
Did some searching.
I may be able to do this with the Puppet service type.
Also, see https://tickets.puppetlabs.com/browse/PUP-3483 for some interesting reading.
I will share what I find.

**Comment by bastelfreak** [comment]
You could manage the service pretty easily with:
```puppet
if $facts['systemd'] {
  service{'tmp.mount':
    ensure   => 'running',
    enabled => true
  }
}
```

I am not sure if this should be handled within this module or a profile, but probably the latter.

**Comment by linuxdan** [comment]
@bastelfreak 
I tried it and it works great.  Running with debug, I see puppet running `/bin/systemctl is-active tmp.mount` and `/bin/systemctl is-enabled tmp.mount`  but there is no such fact as "systemd".

This resource declaration is in a RHEL 7 only manifest file, but I added `provider => 'systemd',` just to be extra-certain.  it runs with no problem.

**NOW** I can close this issue
