### ISSUE TITLE
Regex error when tying to set CPUQuota service limit.

### ISSUE THREAD

**Issue by matt6697** [camptocamp/puppet-systemd#91]
Regex error when tying to set CPUQuota service limit.
```
systemd::service_limits { 'foo.service':
  limits => {
    'CPUQuota' => '75%'
  }
}
 ```
The first part of the regex `Optional['CPUQuota']  => Pattern['^([1-9][0-9]?$|^100)%$'],` never allows a value < 100% 

**Seems to be working with the `'^([1-9][0-9]?|^100)%$'` regex (Tested regex with https://www.freeformatter.com/regex-tester.html)**

**Comment by ekohl** [comment]
The second `^` also looks redundant. Could you come up with a pull request?

**Comment by matt6697** [comment]
Agree, correct regex seems to be `^([1-9][0-9]?|100)%$`

**Comment by matt6697** [comment]
Created PR #92
